# Configuration file for the main script
# This file contains detailed configurations for all LM modules and other required settings.
exp_name: "Pipeline_test"

distiller:
  api_name: "deepinfra"
  llm_config: 
    engine_name: "deepseek-ai/DeepSeek-R1"
    max_tokens: 2000
    temperature: 2
    messages: []
  system_message: "You are an auto-prompting tool. Only provide the final answer. Do not include any reasoning, thoughts, or <think> tags."
  instruction: "Please summarize the documentation provided in a concise manner to describe the usage and functionality of the target. DO NOT generate thinking step"

instructor:
  api_name: "deepinfra"
  llm_config: 
    engine_name: "meta-llama/Meta-Llama-3.1-405B-Instruct"  # Model name for the instructor
    max_tokens: 256                       # Maximum length of each instruction
    temperature: 1                  # Sampling temperature for instructions
    messages: []
  template:                         # Describe the context of instruction generation
    main: "You are a instruction generation tool."
    desc: "Your task is to generate one short instruction at a time. Each instruction must be description of a specific requirement from the compiler description to be tested. Each instruction must add a new layer of incremental complexity to the existing description of requirements for the generation of C program."
    note: "DO NOT generate any code. Instructions must be cohesive to guide the generation of single C program." # Add specific restrictions 
    next: "Generate the next short instruction."  # To guide LLM to generate the next instruction
  separator: "\n"                 # Separator for instructions
  max_instructions: 10              # Maximum number of instructions in a sequence
  device: "cuda"                    # Use auto device mapping for model

coder:
  api_name: "deepinfra"
  system_message: "You are an expert C coding tool."
  instruction: "/* Please create a advanced C program following all the instructions closely. Only generate code and do not include any text.*/"
  device: "cuda"
  llm_config: 
    engine_name: "bigcode/starcoder2-15b-instruct-v0.1"
    max_tokens: 1000
    temperature: 2
    messages: []

# SUT configuration moved to its own top-level section for clarity
SUT:
  language: "c"                   # Programming language of the target
  path_documentation: "config/documentation/c/c_std.md"  # Path to documentation for the target
  path_example_code: null         # Path to example code (if any)
  trigger_to_generate_input: "Please generate a correct and valid code following the given task instructions."   # Trigger string for generating input
  input_hint: "#include <stdlib.h>"  # Hint for input generation
  path_hand_written_prompt: null  # Optional path to a hand-written prompt component
  SUT_string: ""                  # Description of the target (e.g. API name for prompt construction)
  device: "cuda"
  timeout: 10                     # Timeout for SUT operations (e.g., validation)
  folder: "fuzz_outputs"          # Folder for SUT related outputs (e.g., temporary files, fuzz files)
  batch_size: 1                   # Batch size for code generation during SUT validation steps
  temperature: 0.8                # Temperature for code generation during SUT validation steps
  max_length: 1024                # Max length for code generation during SUT validation steps
  log_level: "VERBOSE"               # Logging level for SUT specific logs (INFO, TRACE, VERBOSE)
  template: "fuzzing_with_config_file" # Template name for prompt creation strategy
  lambda_hyper: 0.1               # Hyperparameter lambda for reward calculation
  beta1_hyper: 1.0                # Hyperparameter beta1 for reward calculation
  special_eos: null               # Special End-Of-Sequence token for certain SUTs (e.g., SMT, GO)
  oracle_type: "opt_and_qasm"     # Oracle type for SUT validation (e.g., "crash", "diff", "metamorphic", "opt_and_qasm" for Qiskit)

fuzzer:
  # SUT block removed from here as it's now top-level
  number_of_iterations: 10
  total_time: 1
  resume: false
  otf: false
  log_level: 1                      # Logging level for the Fuzzer component (maps to INFO, TRACE, VERBOSE int enum)

trainer:
  batch_size: 1                     # Batch size for training the Coder LM
  device: "cuda"                    # Device to run the Coder LM training
  sft_ckpt: "checkpoint"
  train_steps: 1000
  grad_acc_steps: 1
  lr: 0.0001
  max_norm: 1.0
  num_warmup_steps: 10
  lora_r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  buffer_size: 100
  prioritization: true
